# Generated by Django 4.0.1 on 2022-04-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='starts',
            new_name='stars',
        ),
    ]
